Ext.define('recibosWeb.view.reemitir.master.ReemitirMasterCtrl', {
    extend: 'Ext.app.ViewController',
    alias : 'controller.reemitir-master',

    control: {
        'reemitir_reemitirgrid': {
            beforerender: 'reemitirLoad'
        }
    },
    onSelectionChange: function (grid, selecion) {

        console.log('esto no lo entiendo');
    },
    /**
     * @autogenerated
     *
     */
    reemitirLoad: function () {
        var me = this;
        // TODO FMM Llevarla a DetailMasterCtrl
        //me.reemitirSearch();
    },

    reemitirReset: function () {
        this.lookupReference('reemitir_reemitirsearchform').getForm().reset();
    },

    /**
     * @autogenerated
     * Load parameters after the search button has been pressed
     * add parameters to a hashmap, and the last step, launches search
     *
     * @param searchBtn button pressed
     *
     */
    reemitirSearch: function () {
        var me = this, store, search = me.lookupReference("reemitir_reemitirsearchform"),
            params = search.getForm().getValues(), value, filters;

        filters = [
            {
                property: 'filter',
                value   : true
            }
        ];

        store = me.getViewModel().getStore('reemitirs');

        Ext.each(Ext.Object.getKeys(params), function (name) {
            value = params[name];
            if (value !== '' && value !== null) {
                filters[filters.length] = {
                    property: name,
                    value   : value
                };
                recibosWeb.lib.Logger.info('property ' + name + 'value ' + value);
            }
        });

        store.setRemoteFilter(true);
        store.clearFilter(true);
        store.filter(filters, null, true);

        store.loadPage(1, {
            callback: function (records, operation, success) {
                if (!success) {
                    if (operation.getError().code === null) {
                        me.error(operation.getError());
                    }
                } else {
                    //TODO ..
                }
            }
        });
    },

    reemitirsDataChanged : function (reemitirs) {
        this.getViewModel().set('reemitirsCount', reemitirs.getCount() > 0 ? reemitirs.getTotalCount() : 0);
    }
});
