Ext.define('recibosWeb.view.periodo.master.PeriodoMasterCtrl', {
    extend: 'Ext.app.ViewController',
    alias : 'controller.periodo-master',

    control: {
        'periodo_periodogrid': {
            beforerender: 'periodoLoad'
        }
    },

    /**
     * @autogenerated
     *
     */
    periodoLoad: function () {
        var me = this;
        // TODO FMM
        //me.periodoSearch();
    },

    periodoReset: function () {
        this.lookupReference('periodo_periodosearchform').getForm().reset();
    },


    onSelectionChange: function (grid, selecion) {
//        this.getViewModel().set('hasAnyActive', this.hasAnyActive(true));
//        this.getViewModel().set('hasAnyInactive', this.hasAnyActive(false));
    },

    /**
     * @autogenerated
     * Load parameters after the search button has been pressed
     * add parameters to a hashmap, and the last step, launches search
     *
     * @param searchBtn button pressed
     *
     */
    periodoSearch: function () {
        var me = this, store, search = me.lookupReference("periodo_periodosearchform"),
            params = search.getForm().getValues(), value, filters;

        filters = [
            {
                property: 'filter',
                value   : true
            }
        ];

        store = me.getViewModel().getStore('periodos');

        Ext.each(Ext.Object.getKeys(params), function (name) {
            value = params[name];
            if (value !== '' && value !== null) {
                filters[filters.length] = {
                    property: name,
                    value   : value
                };
                recibosWeb.lib.Logger.info('property ' + name + 'value ' + value);
            }
        });

        store.setRemoteFilter(true);
        store.clearFilter(true);
        store.filter(filters, null, true);

        store.loadPage(1, {
            callback: function (records, operation, success) {
                if (!success) {
                    if (operation.getError().code === null) {
                        me.error(operation.getError());
                    }
                } else {
                    //TODO ..
                }
            }
        });
    },

    periodosDataChanged : function (periodos) {
        this.getViewModel().set('periodosCount', periodos.getCount() > 0 ? periodos.getTotalCount() : 0);
    }
});
