Ext.define('recibosWeb.view.cabecera.master.CabeceraMasterCtrl', {
    extend: 'Ext.app.ViewController',
    alias : 'controller.cabecera-master',

    control: {
        'cabecera_cabeceragrid': {
            beforerender: 'cabeceraLoad'
        }
    },
    onSelectionChange: function (grid, selecion) {

        console.log('esto no lo entiendo');
    },
    /**
     * @autogenerated
     *
     */
    cabeceraLoad: function () {
        var me = this;
        // TODO FMM Llevarla a DetailMasterCtrl
        //me.cabeceraSearch();
    },

    cabeceraReset: function () {
        this.lookupReference('cabecera_cabecerasearchform').getForm().reset();
    },

    /**
     * @autogenerated
     * Load parameters after the search button has been pressed
     * add parameters to a hashmap, and the last step, launches search
     *
     * @param searchBtn button pressed
     *
     */
    cabeceraSearch: function () {
        var me = this, store, search = me.lookupReference("cabecera_cabecerasearchform"),
            params = search.getForm().getValues(), value, filters;

        filters = [
            {
                property: 'filter',
                value   : true
            }
        ];

        store = me.getViewModel().getStore('cabeceras');

        Ext.each(Ext.Object.getKeys(params), function (name) {
            value = params[name];
            if (value !== '' && value !== null) {
                filters[filters.length] = {
                    property: name,
                    value   : value
                };
                recibosWeb.lib.Logger.info('property ' + name + 'value ' + value);
            }
        });

        store.setRemoteFilter(true);
        store.clearFilter(true);
        store.filter(filters, null, true);

        store.loadPage(1, {
            callback: function (records, operation, success) {
                if (!success) {
                    if (operation.getError().code === null) {
                        me.error(operation.getError());
                    }
                } else {
                    //TODO ..
                }
            }
        });
    },

    cabecerasDataChanged : function (cabeceras) {
        this.getViewModel().set('cabecerasCount', cabeceras.getCount() > 0 ? cabeceras.getTotalCount() : 0);
    }
});
