Ext.define('recibosWeb.view.preemision.master.PreemisionMasterCtrl', {
    extend: 'Ext.app.ViewController',
    alias : 'controller.preemision-master',

    control: {
        'preemision_preemisiongrid': {
            beforerender: 'preemisionLoad'
        }
    },
//    onSelectionChange: function (grid, selecion) {
//
//        console.log('esto no lo entiendo');
//    },
    /**
     * @autogenerated
     *
     */
    preemisionLoad: function () {
        var me = this;
        // TODO FMM Llevarla a DetailMasterCtrl
        me.preemisionSearch();
    },

    preemisionReset: function () {
        this.lookupReference('preemision_preemisionsearchform').getForm().reset();
    },

    /**
     * @autogenerated
     * Load parameters after the search button has been pressed
     * add parameters to a hashmap, and the last step, launches search
     *
     * @param searchBtn button pressed
     *
     */
    preemisionSearch: function () {
        var me = this, store, search = me.lookupReference("preemision_preemisionsearchform"),
            params = search.getForm().getValues(), value, filters;
        filters = [
            {
                property: 'filter',
                value   : true
            }
        ];

        store = me.getViewModel().getStore('preemisions');

        Ext.each(Ext.Object.getKeys(params), function (name) {
            value = Number(params[name]);
            if (value !== '' && value !== null) {
                filters[filters.length] = {
                    property: name,
                    value   : value
                };
                if (recibosWeb.lib.Logger)
                    recibosWeb.lib.Logger.info('property ' + name + 'value ' + value);
            }
        });

        store.setRemoteFilter(true);
        store.clearFilter(true);
        store.filter(filters, null, true);

        store.loadPage(1, {
            callback: function (records, operation, success) {
                if (!success) {
                    if (operation.getError().code === null) {
                        me.error(operation.getError());
                    }
                } else {
                    //TODO ..
                }
            }
        });
    },

    preemisionsDataChanged : function (preemisions) {
        this.getViewModel().set('preemisionsCount', preemisions.getCount() > 0 ? preemisions.getTotalCount() : 0);
    }
});
